[Setup]
AppName=MyHomeLib
PrivilegesRequired=poweruser
DefaultDirName={commonpf}\MyHomeLib\
DefaultGroupName=MyHomeLib
AppID={{B9B6C409-01CB-4AB6-8E4F-403B49A25B56}
OutputDir=.
SourceDir=.
AppVerName=MyHomeLib v.2.3
AppCopyright=© 2023 Oleksiy Penkov
UninstallDisplayIcon={app}\MyHomeLib.exe
WizardImageFile=.\Images\SetupModern20.bmp
WizardSmallImageFile=.\Images\SetupModernSmall20.bmp
SetupIconFile=.\Images\Setup.ico
OutputBaseFilename=Setup_MyHomeLib.2.3x64
AppPublisherURL=https://github.com/OleksiyPenkov/myhomelib/
AppSupportURL=https://github.com/OleksiyPenkov/myhomelib/
AppUpdatesURL=https://github.com/OleksiyPenkov/myhomelib/
UsePreviousAppDir=yes
AllowNoIcons=yes
Compression=lzma/ultra
SolidCompression=yes
LicenseFile=License.txt
VersionInfoVersion=2.3.5.845
ArchitecturesInstallIn64BitMode=x64